import { FloatLayoutLabel } from '@/components/FloatLayoutLabel';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function BlogDetailLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='bg-orange-200 relative'>
      <FloatLayoutLabel>BlogDetailLayout</FloatLayoutLabel>
      <div className='p-10'>{children}</div>
    </div>
  );
}
