import { FloatLayoutLabel } from '@/components/FloatLayoutLabel';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function StudyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className='bg-red-200 relative'>
      <FloatLayoutLabel>StudyLayout</FloatLayoutLabel>
      <div className='pt-2 px-4 font-bold'>StudyLayout</div>
      {children}
    </div>
  );
}
