import { FloatLayoutLabel } from '@/components/FloatLayoutLabel';
import { getDatabaseContents } from '@/libs/notion/databases';
import { blogDatabaseId } from '@/libs/notion/ids';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getPosts = async () => {
  const postsArray = await getDatabaseContents({
    database_id: blogDatabaseId,
    page_size: 12,
    sorts: [
      {
        property: 'Date',
        direction: 'descending',
      },
    ],
    filter: {
      and: [
        {
          property: 'Status',
          select: {
            equals: 'PUBLISH',
          },
        },
        {
          property: 'Date',
          date: {
            is_not_empty: true,
          },
        },
      ],
    },
  });

  return postsArray;
};

export default async function BlogLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getPosts();

  return (
    <div className='bg-green-200 relative'>
      <FloatLayoutLabel>BlogLayout</FloatLayoutLabel>
      <div className='flex'>
        <div className='flex flex-col w-80 p-4 gap-4'>
          <h2 className='font-bold'>Post List</h2>
          {data.results.map((post) => (
            <Link
              key={post.id}
              href={`/blog/${post.id}`}
              className=' hover:underline '
            >
              {/* @ts-expect-error */}
              {post.properties.Title.title[0].plain_text}
            </Link>
          ))}
        </div>
        <div className='p-10'>{children}</div>
      </div>
    </div>
  );
}
